[package]
name = "trident-syscall-stubs-v2"
version = "0.0.1"
edition = "2021"

[dependencies]
solana-sdk = "~2.0.5"
solana-program-runtime = "~2.0.5"
serde = { version = "1", default-features = false }
solana-bpf-loader-program = "~2.0.5"
solana_rbpf = "~0.8"
solana-logger = "~2.0.5"
